### ISSUE TITLE
Enhance "hand" space

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#13]
Do we need a hand space if we can flip card only for one player.

**Comment by jrmi** [comment]
Hand space can be a zone with automatic "Reveal for self" action and allow a player to "take control" of this hand space.

**Comment by Ribakys** [comment]
Is this automatic zone necessary? What could it bring without complicating the system, without confusing the player?
Couldn't a simple zone named with the Hand label be enough?

**Comment by jrmi** [comment]
Actually, I think I already did something for that issue: you can configure automatic actions for a zone. One of the action is "Return for self" so this do the job for our needs. The only problem with that is, if someone else return any card on this zone, he returns the card for himself. However, I'm not going to do something more for now but I keep the issue just in case.

**Comment by jrmi** [comment]
Now we have the zone with automatic actions and the screen for hiding things like money or anything else. Should be enough.
