### ISSUE TITLE
All items should be SVG

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#17]
If all items are svg, we can use more complex ["cursor-pointer"](https://developer.mozilla.org/fr/docs/Web/CSS/pointer-events) options. See this [jsfiddle](https://jsfiddle.net/9zkfodwp/1/)

We also can [drop shadow](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow) on demand (while moving for instance).

**Comment by Ribakys** [comment]
What about the playing card images?

**Comment by jrmi** [comment]
Not needed for now. Close it.
