### ISSUE TITLE
Red color not affordant for connexion link and ask authent link

### ISSUE THREAD

**Issue by numahell** [jrmi/airboardgame#213]
Red color is generally used for delete or cancel actions, not connect or get a link. Maybe blue or green ?

**Comment by jrmi** [comment]
Right, we are going to completely rework the design so we'll take that into account, thanks

**Comment by jrmi** [comment]
The new design is here. What do you think?

**Comment by numahell** [comment]
Hello, there is no link to the design, is this an error ?

**Comment by jrmi** [comment]
The new design is already implemented to official version ;-) -> https://airboardgame.net

**Comment by numahell** [comment]
Ah yes ! it's better indeed.

I've noticed that red color is used for buttons "Save" or "Export", when you want to save game (on edition) or export game (on edition and gameplay), but it is less annoying.

**Comment by jrmi** [comment]
I've also just fixed that now ;-) I close this issue.
