### ISSUE TITLE
Mixed origin  font (google font in css is not in https)

### ISSUE THREAD

**Issue by regilero** [jrmi/airboardgame#224]
in src/index.css we have a `@import url(http://fonts.googleapis.com/css?family=Satisfy);`

That's not in https, in my firefox console I can see this alerte:

`Blocage du chargement du contenu mixte actif (mixed active content) « http://fonts.googleapis.com/css?family=Satisfy »`

**Comment by jrmi** [comment]
Indeed !

**Comment by jrmi** [comment]
Fixed. Thanks for reporting.
