### ISSUE TITLE
UX: connect link blocked waiting for cookie approval

### ISSUE THREAD

**Issue by regilero** [jrmi/airboardgame#225]
I do understand why the 'connect' functionnality is blocked if the cookies are not yet accepted.
Nut I think there're several UX problems on the way it works currently:

* the message does not appear on 'click', only if you wait on the button for the popup to appear. I've missed this info several times (so I've been thinking it was just a buggy 'connect' button). It should be made visible on click.
* the message is wrong. It state that I rejected the cookies, but in fact it's just that cookies are not yet accepted.

**Comment by jrmi** [comment]
Should be fixed can you try it? Thanks for reporting.
