### ISSUE TITLE
Server starting hints to deprecated project

### ISSUE THREAD

**Issue by carsten-engelke** [jrmi/airboardgame#226]
Hi, upon using the steps in readme I get the following hint:
```
C:\Users\Carsten\Projects\airboardgame> npm run server
> airgameboard@0.1.0 server
> echo 'The server is now packaged in separate app. See https://github.com/jrmi/airboardgame-back'
"The server is now packaged in separate app. See https://github.com/jrmi/airboardgame-back"
C:\Users\Carsten\Projects\airboardgame> 
```
However this project is marked as deprecated. How to start a server with the available example games? Could you update the readme file?

**Comment by jrmi** [comment]
Hi,
Thanks to try to install Airboardgame and sorry for your troubles, 

The new server is located here: https://github.com/jrmi/ricochetjs Follow this repository readme to start an instance. You also need to generate some "backend file" on the client repo by executing the following commands:

```
Cd backend

**Comment by jrmi** [comment]
I reworked the Readme and the installation process. What do you think about it now?

**Comment by carsten-engelke** [comment]
This is perfect. Thank you very much! I plan to dig into this project in the upcoming weeks.
