### ISSUE TITLE
Add obvious help on how to unlock locked stuff

### ISSUE THREAD

**Issue by regilero** [jrmi/airboardgame#233]
If you ever lock a content, and then think, well, maybe I'd like to alter it again before relocking it... it seems almost undoable.

I succeed once by exporting the json, alering the locked status in the json, and then re-importing it.

There should be a better way of doing it (or maybe there is one but I missed it)

**Comment by jrmi** [comment]
Not very easy to find the information but you can unlock elements two ways:
- by pressing `l` key while clicking on the locked element
- by long clicking on the element

The first version can be discovered by reading the help modal (click the help button on top right of the screen to open it) and the second option has to be guessed 😄 

I think the issue is more: help on how to unlock elements is too hard to find. I'm working on a better way to show a hint for this situation.

**Comment by romgar** [comment]
Maybe by highlighting the lock icon for a few seconds and allow some interaction with it?

**Comment by regilero** [comment]
Note that currently it's a punition: you try every option to discover effects, checking the locked checkbox  is a direct 'oups, maybe that one should not be checked in fact'.
So a first UX here may be to add a confirmation with an explanation of locked effect (and maybe the `l` trick). But it the same time this may become tedious when you want to lock several elements.
So it could be a warning shown 'once-per-game'.

No other ideas currently... but I'm not an UX expert :-)

**Comment by jrmi** [comment]
I'll try both proposition to see what's the best. Thanks !

**Comment by jrmi** [comment]
Hey @regilero @romgar 

Can you try this version and find the 3 hints I add to help user to know how to unlock an item ?
https://602af743120af3b70022346b--airboardgame.netlify.app

Thanks for your feedback.

**Comment by regilero** [comment]
Cool.

- I like the double click popup (that's the natural thing I try long before the long click)
- The long click is not always easy to perform, but as we have the popup we can retry until we do it the right way
- For the help/hint under the 'lock' checkbox, instead of the long click I would add something more 'feature oriented', like "makes editing and moves harder to perform, use long click to remove lock."

**Comment by jrmi** [comment]
@regilero 
I've updated the feature help. What do you think ?

https://602eaaf39a873638bfeab885--airboardgame.netlify.app/games/

**Comment by regilero** [comment]
yes, OK.
