### ISSUE TITLE
Add delete game action

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#251]

**Comment by dudefaceguy** [comment]
This would help me - I accidentally published two different copies of Go. I retitled one to Abstract Sandbox so it doesn't look as bad :)

**Comment by jrmi** [comment]
In the meantime, you can make it private by unchecking the publish checkbox and save the game again if you want ;-)

**Comment by dudefaceguy** [comment]
Ah great, I did not even think of that! Thanks.

________________________________
