### ISSUE TITLE
Correspondence play support

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#255]
This is already possible by exporting and emailing game states. But, it would be great to have this functionality built in. Instead of having to export and email the game state every move, have the ability to save the game state within airboardgame without having to keep the session alive. That way players could play a correspondence game much more easily. This is especially useful for testing new 2 player games.

**Comment by jrmi** [comment]
I plan to add a 7 days session persistence. Does this solution meet your needs ?

**Comment by dudefaceguy** [comment]
Yes, that should work! You are awesome.

________________________________

**Comment by jrmi** [comment]
Hi @dudefaceguy ,

I've just published a new version with session persistence. Now a game session stay live for 30 days on the same Url.
It's experimental, so don't completely rely on it yet, but if you can test it and give me some feedback.

Thanks.

**Comment by dudefaceguy** [comment]
That's awesome! I will test it now for sure. Thank you!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
