### ISSUE TITLE
White objects turn black when mobile devices are set to "dark" theme

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#256]
For example, in the implementation of Go I recently did, the white stones turn black at night when my phone goes into nighttime dark mode. This leaves players with 2 sets of black stones - until the sun comes up and my phone changes back to daytime theme.

**Comment by jrmi** [comment]
Indeed ! Thanks for reporting.

**Comment by jrmi** [comment]
Can you try this version https://603d5c2a01d02e2754890cfd--airboardgame.netlify.app ? 

Also check that the daytime theme still works ;-)

**Comment by dudefaceguy** [comment]
The tokens seem to be white, but the color in the color picker still looks black even though the RGB values show white. So, the color picker is still broken but the tokens work.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jrmi** [comment]
Dark mode is not so easy to bypass, especially with the actual browser support. Do know what is used on your mobile browser to switch to dark mode ? Some browser extension are aggressive on how they change the colors and you have no choice :cry: 

I think this is the best I can do for now ;-)

I'll publish my modifications and close this ticket until tools improve.

**Comment by dudefaceguy** [comment]
I'm using Android Firefox with DarkReader. Your solution works well - the color picker is not as important as the pieces themselves.

________________________________
