### ISSUE TITLE
Problem from external access

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#257]
Hi,

I've enable my site in local (dev mode and build mode) : It works perfecty.

Then, I've opened the two ports (for external access) : 
- in my firewall (Inbound Rules)
- in my box (freebox)

External access seems ok, but I've this message that remains : `En attente d'une connection...`.

An idea ?

**Comment by jrmi** [comment]
- Can you access the URL `http://<yourserver>/socket.io/` and what's the result ?
- Do you use the create-react-app proxy (should be the default if you have the last version) ? 
- Do you see an error in the browser console ?
- Can you try to use the public socket server to see if it's just an issue of this feature ?

PS: don't forget to update to last version, I've fixed some bugs,  do a `npm ci` in the `backend/` dir.

**Comment by Ribakys** [comment]
- I've updated to last version (both backend and frontend)
- I try `http://localhost:3001/socket.io`, result : `One of x-ricochet-origin, Origin, Referer header is required`.
- I don't know if I use `create-react-app proxy`.
- No error in the browser console
- I try to use the public socket server. Now the message are `Chargement...`

(P.S. I try to connect from external with my phone on Android from Firefox browser)

**Comment by jrmi** [comment]
>     * I try `http://localhost:3001/socket.io`

Can you try it from external access (from your public IP and port)  also don't forget the last `/` it's important.

>     * I don't know if I use `create-react-app proxy`.

By default you use it. In this case you should just need to expose the frontend port from outside. 
 
Can you paste me the frontend configuration file (`.env` file) ?

Do you know [ngork](https://ngrok.com/) ? It's an easy way to test external access without messing up with firewall for development purpose.

Is you goal to host a private instance or just for dev ?

**Comment by Ribakys** [comment]
* `http://localhost:3001/socket.io/` return `{"code":0,"message":"Transport unknown"}` from my local access.
* `http://myPublicIpAdress:3001/socket.io/` return nothing from my local access (computer) and from my external access (mobile phone).
* My frontend `.env` file :

```
##### Front ####

> 

# API URL
REACT_APP_API_ENDPOINT=http://localhost:3001

# Socket configuration
REACT_APP_SOCKET_URL=http://localhost:3001
REACT_APP_SOCKET_PATH=/socket.io

## Public server :

# Set to 1 to remove Welcome dialog
REACT_APP_NO_WELCOME=0
```

* My goal :
  * First, starting in local a session of "test" game, then an external user can connect to this session (to play with 2 players)
  * Creating my new game (to try with custom pictures) and starting to play with external players.
  * Dev new plugins to improve current code (card deck loader, some automations to count score in real time..., etc.).

* I don't know ngork. I will try it.

**Comment by Ribakys** [comment]
I've solved my problem !

For that, in both `.env` files (backend ans frontend), I replace word `localhost` by my local adresse ip (of my box router) :
```
#SERVER_HOST=localhost
SERVER_HOST=192.168.0.37
```
and
```
##REACT_APP_API_ENDPOINT=http://localhost:3001
REACT_APP_API_ENDPOINT=http://192.168.0.37:3001

##REACT_APP_SOCKET_URL=http://localhost:3001
REACT_APP_SOCKET_URL=http://192.168.0.37:3001
```

**Comment by jrmi** [comment]
Good news !

Indeed listening on localhost prevent from listening external connections.

**Comment by jrmi** [comment]
Close the issue as resolved.
