### ISSUE TITLE
Different components snap to different places on the grid.

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#260]
For example, if you to to my Go implementation and try to add a token, jewel, etc. they will snap off-center. However, the black and white image pieces I added will snap on-center. It seems that the boxs for the other components are rectangular, causing them to snap incorrectly. Rounds seem to snap correctly.

**Comment by jrmi** [comment]
Right, items align on the grid from the top-left corner and should be aligned from the item center. I have to rethink the snapping feature to also handle hexagonal or any other shape. This version is too simple.

**Comment by jrmi** [comment]
Should be fixed now. I close it.
