### ISSUE TITLE
Token labels do not appear

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#261]
When I add text to a token, it does not appear on the token.

**Comment by jrmi** [comment]
Can you try this version https://603eb34c5ea31939876b75d6--airboardgame.netlify.app
and tell me if it fix your problem.

**Comment by dudefaceguy** [comment]
Yes, that seems to work! This will make it possible to easily implement stacking games (such as the excellent Tumbleweed). Thank you!

________________________________

**Comment by jrmi** [comment]
Modifications are published.
