### ISSUE TITLE
Drag-to-select breaks after zooming

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#262]
When I zoom out, I can no longer drag to select. I can select normally, but when I drag, the cursor turns into the movement arrows - nothing is selected, and nothing moves. Toggling between select and move mode has no effect.

Okay I got it - drag to select only works if you start on the play area. If I zoom out and start my drag-to-select outside of the background "board" it doesn't work. I was trying to select everything, so I wanted to start outside of the board.

Ah, but it still breaks randomly, and drags around a ghost image of the game instead of doing drag-to-select. Seems like I just need to select and unselect a single thing to fix this.

**Comment by jrmi** [comment]
What is your browser and your pointing device (Mouse? trackpad?) ?

**Comment by dudefaceguy** [comment]
Chrome on the desktop, mouse.

________________________________

**Comment by jrmi** [comment]
I reproduce the bug on Chrome, thanks.

**Comment by jrmi** [comment]
Hi @dudefaceguy, 

I've tried something to solve this bug. Can you try the new version and tell me if you reproduce it or not.

Thanks,

**Comment by jrmi** [comment]
I close this issue unless you succeed to reproduce it ;-)
