### ISSUE TITLE
Lost pictures of a backup when restart server

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#266]
In local, I create a new game and I add new Picture items. These items have a custom back and front pictures from my custom picture files on my hard disc.
Then, I take a backup. To test, I try to load my backup : success, all my items are restored (with view of pictures, back and front)

Finally, I close all my consoles to stop my server.
Then I restart my server and I try to load my previous backup. Result : "Picture" items are restored at the good location and size, but the view of the picture are empty.

In the backup JSON file, I see : 
```
"http://myLocalIpAddress:3001/file/test2/3LrV5ODH7dL_wEVxBo7aM.jpeg"
...
```

**Comment by jrmi** [comment]
What file backend are you using ? By default, files are stored in memory so if you close the server, the uploaded file are lost.

**Comment by Ribakys** [comment]
> What file backend are you using ?
I do not understand the question.


> By default, files are stored in memory so if you close the server, the uploaded file are lost.
That's what I thought. Is there another way (than the default) to store files, or links to those files?

**Comment by jrmi** [comment]
In the backend configuration file (`backend/.env`) I recommend that you put something like:

```sh
FILE_STORAGE=disk
DISK_DESTINATION=/path/to/destination/file
STORE_BACKEND=nedb
NEDB_BACKEND_DIRNAME=/another/path/to/nedbdatabase
```
`DISK_DESTINATION` and `NEDB_BACKEND_DIRNAME` can be any existing path with write permission.

Does that help ?

**Comment by Ribakys** [comment]
Thanks. Problem resolved !
This solution seems to work.

**Comment by jrmi** [comment]
Good news. I close the issue so.
