### ISSUE TITLE
A way to load a card deck ?

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#267]
Is there a way to load a deck of cards?

If not, maybe two ideas for that :

Idea 1:
- A button to choose several picture files into a folder, then create picture items (stacked!) with these pictures files as front picture.
(for the back picture, select all items and choose a picture file in picture back dropzone)

Idea 2:
- Drap-and-drop a new empty picture item.
- Duplicate it, but with a new function (TODO) to duplicate it x times, and stack them.
- With mouse, select the duplicated picture items, and in parameters :
  - select at back picture dropzone a picture file : ok, it works. All duplicated picture items share the same back picture.
  - select at front picture dropzone several picture files (the same number as items) : pb, all duplicated picture items share the first selected picture. TODO : we would map each items with a picture file (to have a different front picture).

**Comment by jrmi** [comment]
Yes, you create deck of card quickly. I've created a (dirty) mini tutorial for you. 

https://www.youtube.com/watch?v=E2lULjNFRl4

You can upload all your card images (even the back side) by drag'n'droping from your desktop to the board. Then copy the url of the back image and paste it to the back image of others card by all selecting them and "mass-edit" the back image field.

You have an action to stack items that have the corresponding action enabled from edit panel.

That's what you are looking for ?

**Comment by Ribakys** [comment]
Wow super ! It works very well.
This is still enough to make a multi-player card game.

Problem solved.

**Comment by jrmi** [comment]
Ok thanks for the feedback. I close the issue.
