### ISSUE TITLE
Different size images problem with both actions AlignAsLine and AlignAsSquare

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#278]
Just a note, this computation works well with same sized images, but is broken with different sizes. I will accept the PR anyway as the common use case is to align card of same size.

_Originally posted by @jrmi in https://github.com/jrmi/airboardgame/pull/277#r595503279_

**Comment by jrmi** [comment]
I close this issue as I think it's solved now. Thanks.
