### ISSUE TITLE
Screen goes black when I try to edit my name, game is unplayable in that session.

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#285]
I tried to edit my name in a session, but before I could erase the default name, the page went completely black and I couldn't access anything. Refreshing or closing and reloading the page has no effect. Clearing the ABG cookie fixes it. But, I still can't change my name.

This is on Chrome mobile and desktop.

Actually, this makes all games unplayable, even in other sessions.

**Comment by jrmi** [comment]
I reproduced it. On the way to fix it. Thank for reporting the issue!

**Comment by jrmi** [comment]
Should be fixed now, even for previous session. Can you try again ?

**Comment by dudefaceguy** [comment]
Works - thanks!

________________________________
