### ISSUE TITLE
Add an action to zoom temporarily

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#290]
Press a key to zoom on mouse position then unzoom on key release.

**Comment by romgar** [comment]
#290 and #289 seem to cover a really close use case.

**Comment by jrmi** [comment]
Yes and may be only one is necessary, we have to decide which one now :D

**Comment by jrmi** [comment]
What can be the action on mobile to make the temp zoom ?

**Comment by jrmi** [comment]
Done for now only on desktop with space key. Need to think on how to do that for mobile.
