### ISSUE TITLE
Dragging items into the bottom of the screen on mobile prevents further interaction in the session

### ISSUE THREAD

**Issue by dudefaceguy** [jrmi/airboardgame#294]
If I drag an object into the bottom area of the mobile screen, where the menu buttons are, I can no longer move objects. Chrome on Android.

**Comment by romgar** [comment]
I managed to reproduce it (but only 1 time) on Android 11 / Chrome:
- Moved a card on the Message button (bottom left corner),
- Impossible afterwards to move it again,
- Couldn't move the board either afterwards (clicking on the "Move" menu button would not change this behaviour),
- Funny fact, double-clicking on other cards on the board would flip down this blocked card.

**Comment by jrmi** [comment]
Hi @dudefaceguy,

I think I fix it, can you try to reproduce it?

**Comment by dudefaceguy** [comment]
The bug still exists for me, and also occurs under different circumstances. I have been testing my game Wild Cities, and I have to reload the page often because of this bug. The attached screenshot shows an example - after moving the disc to the bottom of the screen, I can't interact with anything and must reload the page.
![Screenshot_20210508-082900](https://user-images.githubusercontent.com/79793177/117539206-a0784c80-afd7-11eb-9e56-600b285c8061.png)

This bug also happens seemingly randomly if I have the item menus turned on, even if I avoid the bottom of the screen. Turning off menus avoids the bug except when I drag an item into the bottom menu area.

**Comment by jrmi** [comment]
Thanks a lot for your detailed feedback. I hope it will help me to solve this issue...

**Comment by jrmi** [comment]
I tried a new fix. I think you'll have some strange behaviour sometimes but at least you should be able to continue playing. Tell me if it doesn't works.

**Comment by jrmi** [comment]
Not reproduced. Close it.
