### ISSUE TITLE
UI buttons don't work on latest Firefox Android

### ISSUE THREAD

**Issue by Victor239** [jrmi/airboardgame#301]
Can't switch between different selection tools, open chat etc.

**Comment by jrmi** [comment]
Thanks for reporting it. On the way to reproduce and fix it.

**Comment by jrmi** [comment]
Do you have the address bar in the bottom of the screen? In this case, try to click just above the button (where the buttons are when the bar is visible). Does it works?

**Comment by jrmi** [comment]
May be related to https://github.com/mozilla-mobile/fenix/issues/17991 ?

**Comment by Victor239** [comment]
Ah nevermind it seems to work now. Not sure what it was related to but hopefully it doesn't pop up again.
