### ISSUE TITLE
Allow to configure actions

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#317]
Actions are only simple function with no parameters. We can imagine to allow user to customize an action parameter to avoid action duplication like rotation. We can have only one action rotate with an angle parameter for example.

**Comment by Ribakys** [comment]
An advantage to have action duplication are to be more fast to select a desired action: just by checking a box.
We could same show the action icon near check box.

At the same time, to be able to customize action could be interesting. It's more slower because we need tu fill a text item.
But how to represent these customized actions by an icon ?

All these actions use the same functions (with parameters).

Suggestions : 
- to keep both kind of action via two tabs : a tab "default" and a tab "advanced actions". 
- or, to avoid visual of action duplication, we can create a buton in place of check box plus label, with a general category. When we click it, we show the list of actions (for each, a check box associeted with a label), as like an tree structure from left to right. For example, with push the buton "Rotation", we show list "Rotation 30°", "Rotation 45°", etc.

**Comment by jrmi** [comment]
> An advantage to have action duplication are to be more fast to select a desired action: just by checking a box.
> We could same show the action icon near check box.

Indeed, that's why it bother me ;-)  but I think we need configurable actions.

> 
> At the same time, to be able to customize action could be interesting. It's more slower because we need tu fill a text item.
> But how to represent these customized actions by an icon ?

We can imagine dynamics svg icons? or multiple icons for same action. However, I think sometimes it's not important to have the exact action meaning in the icon if the action is obvious for this specific item.

> 
> All these actions use the same functions (with parameters).
> 
> Suggestions :
> 
>     * to keep both kind of action via two tabs : a tab "default" and a tab "advanced actions".
> 
>     * or, to avoid visual of action duplication, we can create a buton in place of check box plus label, with a general category. When we click it, we show the list of actions (for each, a check box associeted with a label), as like an tree structure from left to right. For example, with push the buton "Rotation", we show list "Rotation 30°", "Rotation 45°", etc.

Yes! I like the two ideas, but I prefer the second. We can also image a that one item in the tree is "Custom rotation" and only if you select it, you show an input to select the exact value. We can add a search box too.


An example:

- Hide/Reveal
  -  [ ] Hide/Reveal
  - [ ] Hide/Reveal and reverse item order
  - [ ] Hide/Reveal for me
  - [ ] Hide/Reveal for other
- Item Rotation
  - [ ] Tap / Untap
  - [ ] Rotation 30°
  - [ ] Rotation 45°
  - [ ] Rotation 90°
  - [ ] Custom rotation
- Stack actions
  - [ ] Stack
  - [ ] Shuffle
  - [ ] Align
  - [ ] Align as a square
- ...

**Comment by Ribakys** [comment]
It's good !

**Comment by jrmi** [comment]
Can also useful to allow action composition like stack+shuffle or shuffle and random rotate.

**Comment by jrmi** [comment]
Hi @Ribakys,

I've added the configurable action system. "Rotate" and "Randomly rotate" actions can be configured if you want to test.

I had to make something a little different than we discuss because I also want to solve #360

You'll also notice that most of the actions are not yet configurable but it's coming ;-)

**Comment by Ribakys** [comment]
> 
> 
> Can also useful to allow action composition like stack+shuffle or shuffle and random rotate.

This could be useful for example, for a "phase of initiation of a new turn" with several actions (always the same) to be carried out in succession.

**Comment by Ribakys** [comment]
> 
> 
> Hi @Ribakys,
> 
> I've added the configurable action system. "Rotate" and "Randomly rotate" actions can be configured if you want to test.
> 
> I had to make something a little different than we discuss because I also want to solve #360
> 
> You'll also notice that most of the actions are not yet configurable but it's coming ;-)
> 
> It's a first version and need to be improved.

Hi @jrmi 

That works well.
The "edit", "up", "down" and "delete" icons are a very good idea. I find it convenient.
This opens the way to many possibilities.

**Comment by jrmi** [comment]
> > Can also useful to allow action composition like stack+shuffle or shuffle and random rotate.
> 
> This could be useful for example, for a "phase of initiation of a new turn" with several actions (always the same) to be carried out in succession.

I fully agree, I'll open another ticket for that.
