### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by nannan9507** [jrmi/airboardgame#333]
First of all, thanks a lot for this amazing project !

Can you develop a feature in mobile ? 
for example, double click is lock the move, change to visit the items in this view.

It's a good chance to combine with the boardgame.io. [https://boardgame.io/]

and can user D.I.Y the game by himself ?

**Comment by jrmi** [comment]
> First of all, thanks a lot for this amazing project !

I'm happy you like it :)

> Can you develop a feature in mobile ?
> for example, double click is lock the move, change to visit the items in this view.

Double click is not always locking, double click is used to trigger the first available action on this item so it can also be to reveal/hide a card or to tap/untap an element and I think this is useful to be able to do the "main" action easily to play a game. But you are right, we need a "zoom" on an item to see it, especially on mobile. I think you mean something like this issues #290 or #289 ? In this case I have not yet found the correct interaction to do that on a mobile. May be by long-pressing the item ?

> 
> It's a good chance to combine with the boardgame.io. [https://boardgame.io/]

I think it's possible and it's a good idea but not for a short term, mainly for the reason I describe above for your next question.

> 
> and can user D.I.Y the game by himself ?

Yes and it's one of the main goal of Airboardgame. If you login, you can access to the game studio creator and create your games online without any coding skills. You can see [here](https://www.youtube.com/watch?v=u2mMk9gRhso&t=5s) a short video on how to do it. This is why boardgame.io is not a priority, I want any game designer to be able to quickly create a game without to have to hire a developer. But I also thinks it can be a good idea to make boardgame.io works for Airboardgame for people that wants to go further and automate some or all phases of their games. Airboardgame become the UI and boardgame.io the brain.

**Comment by jrmi** [comment]
Hey @nannan9507 can I close this ticket (which is not exactly an issue ;-) )?

**Comment by jrmi** [comment]
Close it as it's not an issue. Thanks for your feedback @nannan9507 .

**Comment by nannan9507** [comment]
oh, of course you can close it, I'm so sorry for forget this thing and it's glad to reply me.
I really really like it, thanks a lot
