### ISSUE TITLE
A few remarks in bulk

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#367]
Notes on the version available online:

1- When you select several cards and click on "edit", the left pane appears, but it does not contain the list of actions!
Problem: if you want to add or remove an action, it is necessary to add all the previous actions.
Solution: in the left pane, we could see the list of actions appear (as if we had just added it).

2- In the left pane, there is only the "X" icon to close it. And you can also close by clicking elsewhere than in the left pane. In both cases, our changes are saved.
Problem: how to undo bad handling?
Solution: add a validation icon. And if we click on the "X" icon or if we click outside the left pane, a message appears asking to confirm our choice not to save our changes.

3- In the left pane, the "Add an action ..." combobox is found below the list of actions.
Problem: when you add an action, the combobox is pushed downwards, which means you have to scroll to see it.
Solution 1: place the combobox at the top of the list of actions. This way, we can add new action quickly without having to scroll.
Solution 2: leave the combobox at the bottom. This makes it possible to force the user to always have a visual on all the added actions.

4- When you validate the left pane by clicking on "X", the action menu of the selected elements does not update itself.
Problem: You have to deselect the elements and then reselect them for the action menu to refresh.

5- Some actions like "rotation" can be configured (here we indicate the angle).
Problem: for several different configurations of the same action, the icon is the same in the action menu (of selected items).
Solution 1: we keep this, because by passing the mouse over the icons, we have the configuration information (for example for "rotation", the angle is indicated).
Solution 2: in the icon's svg, we 'automatically' add the configuration information. For example for "rotation", in the svg image we could write the angle, and in a color other than gray.

6- For the "return to me" action, the eye icon is above the element.
Problem: if an element B is found above an element A, we visualize the "eye" icon of A over the visual of B. This can lead to confusion.
Solution: place the eye icon on the element visual. For example for a card, place the eye at the top right.

7- When you move with the mouse selected elements which are "aligned" or "arranged in a square", and release the mouse button, at this moment the empty space between the elements is no longer homogeneous.

8- Just like the views, we could have groups of selected elements (for example for a card, the draw pile, the discard pile).
Visually, after having created a group of selected elements (creation which could be done in the action menu, or in another place by clicking on an icon), we could see a horizontal list appear at the top (in the form of successions of rectangles) from each of the groups.
Clicking on one of the rectangles allows you to select the elements of the corresponding group.
We could also have keyboard shortcuts like for views.
In addition, we could name these groups (eg: draw pile, etc.).

9- When the element "dice with image" is moved, its value changes.
Problem: Players like to move excessively dice, but that shouldn't change the value of the dice.
Solution: double click on the dice to change its value.

10- When we move the digital dice element by accidentally clicking on the "Roll" button, the value of the dice should not change (because our intention was only to move the dice).

11- Ditto for the "Counter" element.

12- In the left pane, in addition to the icons "edit", "up", "down", "delete", we could add a padlock icon to lock the action and avoid bad operations such as changing the parameter or deleting the action.

13- For the "zone" element,
it should be possible to change color (as for the "note" element). It should also be possible to return to the default color.
It would also be necessary to be able to position the text of Label. Currently it is placed on the left, and the writing is vertical. It could also be placed at the top with horizontal writing, or at the bottom, or to the right, etc.

14- When we add new elements to the game board, visually we do not know where they will be placed.
We could use a new (unique) element called "Target", with a target visual. It could be moved and items that are added to the game board are placed on the target item.
We could set it up. For example :
-> definition of the target radius
-> definition of the deposit mode: "All in the same place" (as currently), "Scattering in the target" (the elements are placed at random within the radius of the target).

**Comment by jrmi** [comment]
> 1- When you select several cards and click on "edit", the left pane appears, but it does not contain the list of actions! Problem: if you want to add or remove an action, it is necessary to add all the previous actions. Solution: in the left pane, we could see the list of actions appear (as if we had just added it).

If each items have the same action set, I think it can be done, but what if the actions are different? If we display the intersection of all actions, we can lost actions without knowing it.

> 2- In the left pane, there is only the "X" icon to close it. And you can also close by clicking elsewhere than in the left pane. In both cases, our changes are saved. Problem: how to undo bad handling? Solution: add a validation icon. And if we click on the "X" icon or if we click outside the left pane, a message appears asking to confirm our choice not to save our changes.

Ticket #370 created.

> 3- In the left pane, the "Add an action ..." combobox is found below the list of actions. Problem: when you add an action, the combobox is pushed downwards, which means you have to scroll to see it. Solution 1: place the combobox at the top of the list of actions. This way, we can add new action quickly without having to scroll. Solution 2: leave the combobox at the bottom. This makes it possible to force the user to always have a visual on all the added actions.

Issue #372 created.

> 4- When you validate the left pane by clicking on "X", the action menu of the selected elements does not update itself. Problem: You have to deselect the elements and then reselect them for the action menu to refresh.

Issue #371 created

> 5- Some actions like "rotation" can be configured (here we indicate the angle). Problem: for several different configurations of the same action, the icon is the same in the action menu (of selected items). Solution 1: we keep this, because by passing the mouse over the icons, we have the configuration information (for example for "rotation", the angle is indicated). Solution 2: in the icon's svg, we 'automatically' add the configuration information. For example for "rotation", in the svg image we could write the angle, and in a color other than gray.

Issue #373 created.

> 6- For the "return to me" action, the eye icon is above the element. Problem: if an element B is found above an element A, we visualize the "eye" icon of A over the visual of B. This can lead to confusion. Solution: place the eye icon on the element visual. For example for a card, place the eye at the top right.

What if there is an important information here like card cost or something?

> 7- When you move with the mouse selected elements which are "aligned" or "arranged in a square", and release the mouse button, at this moment the empty space between the elements is no longer homogeneous.

Did you notice that on all games or only for those with an item or global grid configured?

> 8- Just like the views, we could have groups of selected elements (for example for a card, the draw pile, the discard pile). Visually, after having created a group of selected elements (creation which could be done in the action menu, or in another place by clicking on an icon), we could see a horizontal list appear at the top (in the form of successions of rectangles) from each of the groups. Clicking on one of the rectangles allows you to select the elements of the corresponding group. We could also have keyboard shortcuts like for views. In addition, we could name these groups (eg: draw pile, etc.).

Issue #374 created.


> 9- When the element "dice with image" is moved, its value changes. Problem: Players like to move excessively dice, but that shouldn't change the value of the dice. Solution: double click on the dice to change its value.

I think you can already do that by checking  the corresponding option in the edit panel of this item.

> 10- When we move the digital dice element by accidentally clicking on the "Roll" button, the value of the dice should not change (because our intention was only to move the dice).

I hesitate to remove this dice in futur. Do you found it useful? Do you have use cases?

> 11- Ditto for the "Counter" element.

Issue # 375

> 12- In the left pane, in addition to the icons "edit", "up", "down", "delete", we could add a padlock icon to lock the action and avoid bad operations such as changing the parameter or deleting the action.

I need to think about it.

> 13- For the "zone" element, it should be possible to change color (as for the "note" element). It should also be possible to return to the default color. It would also be necessary to be able to position the text of Label. Currently it is placed on the left, and the writing is vertical. It could also be placed at the top with horizontal writing, or at the bottom, or to the right, etc.

Issue #376

> 14- When we add new elements to the game board, visually we do not know where they will be placed. We could use a new (unique) element called "Target", with a target visual. It could be moved and items that are added to the game board are placed on the target item. We could set it up. For example : -> definition of the target radius -> definition of the deposit mode: "All in the same place" (as currently), "Scattering in the target" (the elements are placed at random within the radius of the target).

Currently, the new elements is placed at the center of the screen, I found what you propose a little more difficult. Do you have any reason for that ?

**Comment by jrmi** [comment]
Hey @Ribakys do you anay answer to this thread or can I closed it as other issues are opened?

**Comment by Ribakys** [comment]
> 1- When you select several cards and click on "edit", the left pane appears, but it does not contain the list of actions! Problem: if you want to add or remove an action, it is necessary to add all the previous actions. Solution: in the left pane, we could see the list of actions appear (as if we had just added it).

> If each items have the same action set, I think it can be done, but what if the actions are different? If we display the intersection of all actions, we can lose actions without knowing it. What do you think?

I see two solutions : 
 - We can see all actions only in case of each items have the same action set (currently, it's not the case).
 - We can create notion of  'group' with these features : 
   - A list of item that shared strictly same actions.
   - Each item can belong to only one group.
   - If an item belong to a group, we can modify only group action and not item actions (lock this).


> 6- For the "return to me" action, the eye icon is above the element. Problem: if an element B is found above an element A, we visualize the "eye" icon of A over the visual of B. This can lead to confusion. Solution: place the eye icon on the element visual. For example for a card, place the eye at the top right.

>What if there is an important information here like card cost or something?

Yes indeed. I think we need to create an new issue to think about a solution. For example : 
- Adjust opacity.
- Different positioning on the item that can be adjusted as needed in the left pane.


> 7- When you move with the mouse selected elements which are "aligned" or "arranged in a square", and release the mouse button, at this moment the empty space between the elements is no longer homogeneous.

> Did you notice that on all games or only for those with an item or global grid configured?

I notice that on all games.


> 9- When the element "dice with image" is moved, its value changes. Problem: Players like to move excessively dice, but that shouldn't change the value of the dice. Solution: double click on the dice to change its value.

> I think you can already do that by checking  the corresponding option in the edit panel of this item. I think both behaviour can be useful.

Oh ok, I hadn't seen that the functionality already existed. Perfect !


> 10- When we move the digital dice element by accidentally clicking on the "Roll" button, the value of the dice should not change (because our intention was only to move the dice).

> I hesitate to remove this dice in futur. Do you found it useful? Do you have use cases?

Pb with rolling it's ok.
I don't have a use case, but it's more convenient if you're throwing, for example, a 30-sided die than loading 30 frames. In the upper right pane, we can create a new tab instead of "Standard". For example, "Other" tab or "Advanced" tab because it's not a standard item.


> 12- In the left pane, in addition to the icons "edit", "up", "down", "delete", we could add a padlock icon to lock the action and avoid bad operations such as changing the parameter or deleting the action.

> I need to think about it.
Ok.


> 14- When we add new elements to the game board, visually we do not know where they will be placed. We could use a new (unique) element called "Target", with a target visual. It could be moved and items that are added to the game board are placed on the target item. We could set it up. For example : -> definition of the target radius -> definition of the deposit mode: "All in the same place" (as currently), "Scattering in the target" (the elements are placed at random within the radius of the target).

> Currently, the new elements is placed at the center of the screen, I found what you propose a little more difficult to use. Do you have something that bother you specifically with this behaviour?

When we create and edit a new game it can get tedious. Perhaps a compromise could be to show or hide a "+" image that shows the center of the screen. So to place the new items, we display the center of the screen and we move the view (to move the place where the items are placed).

**Comment by jrmi** [comment]
> 
> I see two solutions :
> 
>     * We can see all actions only in case of each items have the same action set (currently, it's not the case).
> 
>     * We can create notion of  'group' with these features :
>       
>       * A list of item that shared strictly same actions.
>       * Each item can belong to only one group.
>       * If an item belong to a group, we can modify only group action and not item actions (lock this).

Yes, I think the first one can be not too hard to do. However the group concept is also interesting but much difficult to do. -> issue #384

> 
> Yes indeed. I think we need to create an new issue to think about a solution. For example :
> 
>     * Adjust opacity.
> 
>     * Different positioning on the item that can be adjusted as needed in the left pane.

-> Issue #385

> 
> I notice that on all games.

I failed to reproduce it. Do you have an example?
 
> > I hesitate to remove this dice in futur. Do you found it useful? Do you have use cases?
> 
> Pb with rolling it's ok. I don't have a use case, but it's more convenient if you're throwing, for example, a 30-sided die than loading 30 frames. In the upper right pane, we can create a new tab instead of "Standard". For example, "Other" tab or "Advanced" tab because it's not a standard item.

Ook why not, good idea.

> 
> When we create and edit a new game it can get tedious. Perhaps a compromise could be to show or hide a "+" image that shows the center of the screen. So to place the new items, we display the center of the screen and we move the view (to move the place where the items are placed).

I like this idea. The "+" could be visible only when the "Add item" panel is open.

**Comment by jrmi** [comment]
I close this one as I think I've opened all independent issues.
