### ISSUE TITLE
Howto : default settings for adding cards?

### ISSUE THREAD

**Issue by El-Gavy** [jrmi/airboardgame#380]
Hi,

Sorry, this is not a bug report or a feature request but I didn't know elsewhere post this.

I am trying to create a game and I need to create like 400+ different cards, which all have the same back image and need the same actions (make visible for me only, make visible for all, engage, stack and mix).

I found two ways to do so but which are not optimal : 
- Create one card with all the needed properties and then duplicate it and change the image at each time to create all the other cards
- Drag and drop all the images of the cards and then change the settings and back image of each card

Is there another easy way to do so?

Thanks in advance for your answer!

**Comment by jrmi** [comment]
Hey @El-Gavy 

You can ask your question here without problem or you can go on the *discussions* section of this github project if you prefer.

I think the faster way to create your deck (I assume about 3 minutes) is to drag and drop all your images, then select them all and modify the back image and the actions for all cards at the same time. You can see an example in this quick video https://www.youtube.com/watch?v=E2lULjNFRl4

Does it help you ?

**Comment by El-Gavy** [comment]
Thanks a lot @jrmi I tried it on a few cards and it seems to be working as expected!
