### ISSUE TITLE
Actions remove seems not appear

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#400]
We select several items.
We add action "Remove"(at left pane).
Then, we select these items : action not appears.

**Comment by Ribakys** [comment]
This action appears very late.

**Comment by jrmi** [comment]
Indeed you need to unselect and reselect these items to see the remove action (this need to be fixed!). However the remove action is visible only when you're on edit mode for this item (i.e you've clicked on the pen icon) that may explains the "delay" before it appears.

**Comment by Ribakys** [comment]
Ok. Perhaps we could mention in the documentation how to remove an item (and that the remove-action icon appears when we select the edit mode).
