### ISSUE TITLE
real time collaboration via y.js

### ISSUE THREAD

**Issue by henryoswald** [jrmi/airboardgame#431]
Hi,

I came across airboardgame earlier via the y.js discord and wanted to say hi, but I struggled to find an email beyond the abuse-report@airboardgame.com so I thought a github ticket might be appropriate.

I saw you are looking at using y.js for syncing user state across games and wondered if I could speak to you more about this. I am currently building a backend with persistence for y.js, https://github.com/firesync-org/firesync , I was wondering if you would be open to helping me understand your usage of y.js a little bit, I am trying to work out exactly what features and functionality people are looking for out of the box. Your input would be really useful to me. I think it’s still early days for you and y.js so your thoughts would be extra useful to me.

I've spent a fair bit of time working in the real time collaboration space, my previous company sharelatex (overleaf.com now)  is a collaborative editor for academics, but built on Operational Transformation, not CRDT’s.

If you are up for a little chat some time it would be amazing.

Thank you and sorry for spamming your issues.

**Comment by jrmi** [comment]
Answered by mail.
